export const JWT_MODULE_OPTIONS = 'JWT_MODULE_OPTIONS'
export const ACCESS_JWT_STRATEGY = 'ACCESS_JWT_STRATEGY'
export const REFRESH_JWT_STRATEGY = 'REFRESH_JWT_STRATEGY'
export const GOOGLE_OAUTH_STRATEGY = 'GOOGLE_OAUTH_STRATEGY'
