export enum ESettingsName {
	TAP_INTERVAL = 'TAP_INTERVAL',
	TRY_CHANCE = 'TRY_CHANCE',
	ZERO_LEVEL_CHANCE = 'ZERO_LEVEL_CHANCE',
	FIRST_LEVEL_CHANCE = 'FIRST_LEVEL_CHANCE',
	SECOND_LEVEL_CHANCE = 'SECOND_LEVEL_CHANCE',
	THIRD_LEVEL_CHANCE = 'THIRD_LEVEL_CHANCE',
	CRAFT_NULL_CHANCE = 'CRAFT_NULL_CHANCE',
	CRAFT_ONE_CHANCE = 'CRAFT_ONE_CHANCE',
	CRAFT_TWO_CHANCE = 'CRAFT_TWO_CHANCE'
}
